class BaseAgent:
    """
    A base class for all agents in the dialogue system.
    This class provides shared functionality and attributes that can be
    inherited by specific agents, such as MemoryAgent, DialogueAgent, and SummaryAgent.
    """

    def __init__(self, client):
        """
        Initializes the BaseAgent with a client, which could be an API client
        or any other shared resource necessary for the operation of the agent.

        Parameters:
        - client: An instance of a client used for making API calls or executing tasks.
        """
        self.client = client

    def preprocess_input(self, user_input):
        """
        A method to preprocess user input before it is handled by the agent.
        This can be overridden by subclasses to provide specific preprocessing logic.

        Parameters:
        - user_input: The raw input from the user as a string.

        Returns:
        - A preprocessed version of the user input.
        """
        # Example preprocessing, can be customized by subclasses
        return user_input.strip().lower()

    def postprocess_response(self, response):
        """
        A method to postprocess the response generated by the agent before
        it is returned to the user. This can be overridden by subclasses to
        provide specific postprocessing logic.

        Parameters:
        - response: The raw response generated by the agent.

        Returns:
        - A postprocessed version of the response.
        """
        # Example postprocessing, can be customized by subclasses
        return response
